
name : CI-Pipeline-Worflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  name: Lint 
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r tests/requirement.txt
    - name: install flake8
      run: |
        pip install flake8
    - name: Run Lint in app/ and tests/ directories
      run: |
        flake8 app/ tests/
  name: Test
  needs: Lint
  runs-on: ubuntu-latest
  steps:
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r tests/requirement.txt
    - name: Run tests
      run: |
        pytest tests/ -v --cov=src
  name: Build
  needs: Test
  runs-on: ubuntu-latest
  steps:
    - name: Build the package
      run: |
        python -m Build
    - name: Upload results
      uses: actions/upload-artifact@v3